"""initial_schema

Revision ID: 1f57fc4f4605
Revises: 
Create Date: 2026-01-03 01:53:07.206197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f57fc4f4605'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('subscription_tier', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), server_default='inactive', nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_status', sa.String(), nullable=True),
    sa.Column('stripe_current_period_end', sa.Integer(), nullable=True),
    sa.Column('stripe_current_period_end_dt', sa.DateTime(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_updated_at', sa.DateTime(), nullable=True),
    sa.Column('usage_screenshots', sa.Integer(), nullable=True),
    sa.Column('usage_batch_requests', sa.Integer(), nullable=True),
    sa.Column('usage_api_calls', sa.Integer(), nullable=True),
    sa.Column('usage_clean_transcripts', sa.Integer(), nullable=True),
    sa.Column('usage_unclean_transcripts', sa.Integer(), nullable=True),
    sa.Column('usage_audio_downloads', sa.Integer(), nullable=True),
    sa.Column('usage_video_downloads', sa.Integer(), nullable=True),
    sa.Column('usage_reset_date', sa.DateTime(), nullable=True),
    sa.Column('usage_reset_at', sa.DateTime(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('api_key_created_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('screenshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('full_page', sa.Boolean(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), nullable=True),
    sa.Column('remove_elements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=True),
    sa.Column('baseline_screenshot_id', sa.String(), nullable=True),
    sa.Column('difference_percentage', sa.Float(), nullable=True),
    sa.Column('has_changes', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['baseline_screenshot_id'], ['screenshots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screenshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screenshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_screenshots_status', ['status'], unique=False)
        batch_op.create_index('ix_screenshots_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_screenshots_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_screenshots_user_url', ['user_id', 'url'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('transcript_downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(), nullable=False),
    sa.Column('transcript_type', sa.String(), nullable=False),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('file_format', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_downloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcript_downloads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_downloads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_downloads_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcript_downloads_youtube_id'), ['youtube_id'], unique=False)
        batch_op.create_index('ix_transcripts_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_downloads', schema=None) as batch_op:
        batch_op.drop_index('ix_transcripts_user_created')
        batch_op.drop_index(batch_op.f('ix_transcript_downloads_youtube_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_downloads_user_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_downloads_id'))
        batch_op.drop_index(batch_op.f('ix_transcript_downloads_created_at'))

    op.drop_table('transcript_downloads')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_created_at'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('screenshots', schema=None) as batch_op:
        batch_op.drop_index('ix_screenshots_user_url')
        batch_op.drop_index(batch_op.f('ix_screenshots_user_id'))
        batch_op.drop_index('ix_screenshots_user_created')
        batch_op.drop_index('ix_screenshots_status')
        batch_op.drop_index(batch_op.f('ix_screenshots_created_at'))

    op.drop_table('screenshots')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_api_key'))

    op.drop_table('users')
    # ### end Alembic commands ###
