#!/usr/bin/env python3
"""
generate_sitemap.py - route-driven sitemap builder for pixelperfectapi.net

Two modes:

  1) EXTRACT - scan your React Router source and emit routes.txt
       python generate_sitemap.py --extract ../../frontend/src

  2) BUILD - read routes.txt and emit a validated sitemap.xml
       python generate_sitemap.py

Why extract instead of hand-listing? Because a React SPA returns HTTP 200 for
*every* path - including ones that do not exist. curl cannot tell you whether a
route is real. Your router config can. Extracting from source means the sitemap
can never contain a soft-404 URL.

WORKFLOW
--------
  python generate_sitemap.py --extract ../../frontend/src   # writes routes.txt
  <review routes.txt by hand - delete private/auth-only paths>
  python generate_sitemap.py                                # writes sitemap.xml
  <copy sitemap.xml to frontend/public/ and redeploy>

routes.txt format - one path per line, '#' starts a comment:
    /
    /pricing
    /docs/quickstart          priority=0.8
    /help/getting-started     changefreq=monthly priority=0.7
"""

import argparse
import re
import sys
import xml.dom.minidom
from datetime import date
from pathlib import Path
from xml.sax.saxutils import escape

BASE = "https://pixelperfectapi.net"
ROUTES_FILE = Path("routes.txt")
OUT_FILE = Path("sitemap.xml")
TODAY = date.today().isoformat()

# Must mirror the Disallow rules in robots.txt. Listing a disallowed URL in a
# sitemap is a Search Console warning, so these are filtered automatically.
DISALLOWED = (
    "/dashboard", "/screenshot", "/activity", "/history", "/batch",
    "/subscription", "/settings", "/account-settings", "/change-password",
    "/forgot-password", "/forgot-username", "/reset", "/static/",
)

# Alias routes that render the same component as a canonical route. They are
# excluded from the sitemap and given a canonical tag pointing at the target,
# so link equity consolidates instead of splitting.
ALIASES = {
    "/documentation": "/docs",
    "/help-center":   "/help",
    "/api-status":    "/status",
    "/signup":        "/register",
}

# Paths that are real but should not be crawled priorities - tune freely.
DEFAULT_RULES = [
    ("/",       "weekly",  "1.0"),
    ("/pricing", "monthly", "0.9"),
    ("/docs",    "weekly",  "0.9"),
    ("/help",    "weekly",  "0.8"),
]
SECTION_DEFAULTS = {
    "/help/article/": ("monthly", "0.7"),
    "/guides/": ("monthly", "0.7"),
    "/blog/": ("monthly", "0.6"),
    "/docs/": ("monthly", "0.7"),
    "/help/": ("monthly", "0.7"),
}
FALLBACK = ("monthly", "0.5")
LEGAL_PATHS = ("/terms", "/privacy", "/refund", "/legal")


# ---------------------------------------------------------------- extract ---

ROUTE_PATTERNS = [
    re.compile(r'<Route\s+[^>]*?path\s*=\s*["\']([^"\']+)["\']'),
    re.compile(r'<Route\s+[^>]*?path\s*=\s*\{\s*["\']([^"\']+)["\']\s*\}'),
    re.compile(r'\bpath\s*:\s*["\']([^"\']+)["\']'),   # object route config
]


def extract_routes(src_dir: Path) -> list[str]:
    if not src_dir.is_dir():
        sys.exit(f"ERROR: not a directory: {src_dir}")

    found: set[str] = set()
    scanned = 0
    for ext in ("*.js", "*.jsx", "*.ts", "*.tsx"):
        for f in src_dir.rglob(ext):
            if "node_modules" in f.parts:
                continue
            scanned += 1
            try:
                text = f.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            for pat in ROUTE_PATTERNS:
                for m in pat.finditer(text):
                    found.add(m.group(1))

    print(f"  scanned {scanned} source files", file=sys.stderr)

    clean, dropped = [], []
    for r in sorted(found):
        if r in ("*", "/*") or ":" in r or "*" in r:
            dropped.append(r)          # wildcards + :params are not real URLs
            continue
        if not r.startswith("/"):
            r = "/" + r                # React Router v6 relative child routes
        clean.append(r)

    if dropped:
        print(f"  dropped {len(dropped)} dynamic/wildcard route(s): "
              f"{', '.join(dropped)}", file=sys.stderr)
    return clean


def write_routes_file(routes: list[str]) -> None:
    lines = [
        "# routes.txt - one path per line. '#' starts a comment.",
        "# Generated by --extract. REVIEW THIS BY HAND before building:",
        "#   * delete anything behind auth or not meant for search",
        "#   * delete anything that renders an empty/placeholder page",
        "#   * add per-line overrides like:  /docs/errors  priority=0.6",
        "",
    ]
    kept = 0
    for r in routes:
        if r.startswith(DISALLOWED):
            lines.append(f"# (robots-disallowed) {r}")
        else:
            lines.append(r)
            kept += 1
    ROUTES_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  wrote {ROUTES_FILE} with {kept} candidate route(s)",
          file=sys.stderr)


# ------------------------------------------------------------------ build ---

def parse_routes_file() -> list[tuple[str, str, str]]:
    if not ROUTES_FILE.exists():
        sys.exit(f"ERROR: {ROUTES_FILE} not found. Run --extract first, or "
                 f"create it by hand (one path per line).")

    out = []
    for raw in ROUTES_FILE.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        path = parts[0]
        opts = dict(p.split("=", 1) for p in parts[1:] if "=" in p)
        freq, prio = defaults_for(path)
        out.append((path,
                    opts.get("changefreq", freq),
                    opts.get("priority", prio)))
    return out


def defaults_for(path: str) -> tuple[str, str]:
    for p, freq, prio in DEFAULT_RULES:
        if path == p:
            return freq, prio
    if path.startswith(LEGAL_PATHS):
        return "yearly", "0.3"
    for prefix, (freq, prio) in SECTION_DEFAULTS.items():
        if path.startswith(prefix):
            return freq, prio
    return FALLBACK


def build(routes: list[tuple[str, str, str]]) -> str:
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    seen, skipped = set(), []

    for path, freq, prio in routes:
        if path.startswith(DISALLOWED):
            skipped.append(path)
            continue
        if path in ALIASES:
            print(f"  skipped alias {path} -> canonical {ALIASES[path]}",
                  file=sys.stderr)
            continue
        loc = BASE + path
        if loc in seen:
            continue
        seen.add(loc)
        lines += ["  <url>",
                  f"    <loc>{escape(loc)}</loc>",
                  f"    <lastmod>{TODAY}</lastmod>",
                  f"    <changefreq>{freq}</changefreq>",
                  f"    <priority>{prio}</priority>",
                  "  </url>"]

    lines.append("</urlset>")

    if skipped:
        print(f"  skipped {len(skipped)} robots-disallowed path(s)",
              file=sys.stderr)
    print(f"  wrote {len(seen)} URLs", file=sys.stderr)
    if len(seen) > 50000:
        print("  WARNING: over 50,000 URLs - split into a sitemap index",
              file=sys.stderr)
    return "\n".join(lines) + "\n"


def validate(path: Path) -> bool:
    raw = path.read_bytes()
    ok = True
    if raw.startswith(b"\xef\xbb\xbf"):
        print("  FAIL: file begins with a UTF-8 BOM", file=sys.stderr)
        ok = False
    if not raw.startswith(b"<?xml"):
        print("  FAIL: XML declaration is not at byte 0", file=sys.stderr)
        ok = False
    if b"<!--" in raw[:200]:
        print("  FAIL: file starts with a comment - this is the exact bug "
              "that caused 'Unsupported file format'", file=sys.stderr)
        ok = False
    try:
        xml.dom.minidom.parse(str(path))
    except Exception as exc:
        print(f"  FAIL: not well-formed XML - {exc}", file=sys.stderr)
        ok = False
    if ok:
        print("  OK: well-formed, no BOM, declaration at byte 0",
              file=sys.stderr)
    return ok


# ------------------------------------------------------------------- main ---

if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--extract", metavar="SRC_DIR",
                    help="scan React source for <Route path=...> and write routes.txt")
    ap.add_argument("--check", action="store_true",
                    help="validate an existing sitemap.xml and exit")
    args = ap.parse_args()

    if args.check:
        sys.exit(0 if validate(OUT_FILE) else 1)

    if args.extract:
        write_routes_file(extract_routes(Path(args.extract)))
        print("\n  NEXT: open routes.txt, delete anything that should not be "
              "indexed,\n        then run:  python generate_sitemap.py",
              file=sys.stderr)
        sys.exit(0)

    OUT_FILE.write_bytes(build(parse_routes_file()).encode("utf-8"))
    sys.exit(0 if validate(OUT_FILE) else 1)

# #!/usr/bin/env python3
# """
# generate_sitemap.py - build a Google-valid sitemap.xml for pixelperfectapi.net

# WHY THIS EXISTS
# ---------------
# The previous sitemap failed with "Unsupported file format" because the whole
# file was wrapped in an HTML comment (<!-- ... -->) and its URLs pointed at
# onetechly.com. This script makes both mistakes impossible:

#   * The <?xml ...?> declaration is always written at byte 0.
#   * Output is UTF-8 with NO byte-order mark and LF line endings.
#   * Every <loc> is built from BASE, so the domain can never drift.
#   * URLs are checked against the robots.txt disallow list before being written.

# USAGE
# -----
#     python generate_sitemap.py            # writes ./sitemap.xml and validates it
#     python generate_sitemap.py --check    # validate an existing sitemap.xml only

# Then upload sitemap.xml to your web root and, in Google Search Console,
# Sitemaps -> enter "sitemap.xml" -> Submit.
# """

# import sys
# import xml.dom.minidom
# from datetime import date
# from pathlib import Path
# from xml.sax.saxutils import escape

# BASE = "https://pixelperfectapi.net"
# OUT = Path("sitemap.xml")
# TODAY = date.today().isoformat()

# # Mirrors the Disallow rules in robots.txt. A URL matching any of these
# # must never appear in the sitemap - Google flags that as a conflict.
# DISALLOWED_PREFIXES = (
#     "/dashboard", "/screenshot", "/activity", "/history", "/batch",
#     "/subscription", "/settings", "/account-settings", "/change-password",
#     "/api/", "/files/", "/user/", "/debug/",
# )

# # ---------------------------------------------------------------------------
# # EDIT BELOW: (path, changefreq, priority)
# # Only list URLs that return HTTP 200 and render real HTML to a crawler.
# # ---------------------------------------------------------------------------

# MARKETING = [
#     ("/",         "weekly",  "1.0"),
#     ("/pricing",  "monthly", "0.9"),
#     ("/about",    "monthly", "0.5"),
#     ("/contact",  "monthly", "0.5"),
# ]

# DOCS = [
#     ("/docs",                    "weekly",  "0.9"),
#     ("/docs/quickstart",         "monthly", "0.8"),
#     ("/docs/authentication",     "monthly", "0.7"),
#     ("/docs/full-page",          "monthly", "0.7"),
#     ("/docs/element-selection",  "monthly", "0.7"),
#     ("/docs/webhooks",           "monthly", "0.7"),
#     ("/docs/batch-jobs",         "monthly", "0.7"),
#     ("/docs/errors",             "monthly", "0.6"),
#     ("/docs/rate-limits",        "monthly", "0.6"),
# ]

# # TODO: replace with your real 31 Help Center slugs.
# HELP = [
#     ("/help",                     "weekly",  "0.8"),
#     ("/help/getting-started",     "monthly", "0.7"),
#     ("/help/api-keys",            "monthly", "0.7"),
#     ("/help/billing",             "monthly", "0.6"),
#     ("/help/troubleshooting",     "monthly", "0.6"),
# ]

# LEGAL = [
#     ("/terms",   "yearly", "0.3"),
#     ("/privacy", "yearly", "0.3"),
# ]

# AUTH = [
#     ("/login",    "yearly", "0.4"),
#     ("/register", "yearly", "0.4"),
# ]

# SECTIONS = MARKETING + DOCS + HELP + LEGAL + AUTH

# # ---------------------------------------------------------------------------


# def build() -> str:
#     lines = ['<?xml version="1.0" encoding="UTF-8"?>',
#              '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']

#     seen, skipped = set(), []
#     for path, freq, prio in SECTIONS:
#         if path.startswith(DISALLOWED_PREFIXES):
#             skipped.append(path)
#             continue
#         loc = BASE + path
#         if loc in seen:
#             continue
#         seen.add(loc)
#         lines += [
#             "  <url>",
#             f"    <loc>{escape(loc)}</loc>",
#             f"    <lastmod>{TODAY}</lastmod>",
#             f"    <changefreq>{freq}</changefreq>",
#             f"    <priority>{prio}</priority>",
#             "  </url>",
#         ]

#     lines.append("</urlset>")

#     if skipped:
#         print(f"  skipped {len(skipped)} robots-disallowed path(s): "
#               f"{', '.join(skipped)}", file=sys.stderr)
#     print(f"  wrote {len(seen)} URLs", file=sys.stderr)
#     return "\n".join(lines) + "\n"


# def validate(path: Path) -> bool:
#     raw = path.read_bytes()
#     ok = True
#     if raw.startswith(b"\xef\xbb\xbf"):
#         print("  FAIL: file begins with a UTF-8 BOM", file=sys.stderr)
#         ok = False
#     if not raw.startswith(b"<?xml"):
#         print("  FAIL: file does not begin with the XML declaration",
#               file=sys.stderr)
#         ok = False
#     try:
#         xml.dom.minidom.parse(str(path))
#     except Exception as exc:
#         print(f"  FAIL: not well-formed XML - {exc}", file=sys.stderr)
#         ok = False
#     if ok:
#         print("  OK: well-formed, no BOM, declaration at byte 0",
#               file=sys.stderr)
#     return ok


# if __name__ == "__main__":
#     if "--check" in sys.argv:
#         sys.exit(0 if validate(OUT) else 1)
#     OUT.write_bytes(build().encode("utf-8"))
#     sys.exit(0 if validate(OUT) else 1)